# Generated by Django 5.2.3 on 2025-06-19 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubmission',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answersubmission',
            name='chosen_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answerdb'),
        ),
    ]
