# Generated by Django 5.2.3 on 2025-06-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testsubmission_time_taken_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsubmission',
            options={'verbose_name': 'Test Submission', 'verbose_name_plural': 'Test Submissions'},
        ),
        migrations.AlterUniqueTogether(
            name='testsubmission',
            unique_together={('user', 'test')},
        ),
    ]
