[phases.setup]
nixPkgs = [
  "python311",
  "texlive.scheme-medium",
  "texlive.enumitem",
  "texlive.tikz",
  "texlive.fancyhdr",
  "texlive.multicol",
  "texlive.graphics"
]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python manage.py runserver 0.0.0.0:$PORT"
