[phases.setup]
nixPkgs = ["python311", "texlive.combined.scheme-medium"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn YOUR_PROJECT_NAME.wsgi:application --bind 0.0.0.0:$PORT"
