# Generated by Django 5.2.3 on 2025-07-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorders',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
