# Generated by Django 5.2.3 on 2025-07-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentorders_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorders',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='paymentorders',
            name='price',
        ),
    ]
