# Generated by Django 5.2.3 on 2025-07-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_testtypedb_testdb_test_belong_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtypedb',
            name='image_url',
            field=models.ImageField(null=True, upload_to='media/testtypes'),
        ),
    ]
