# Generated by Django 5.2.3 on 2025-07-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_testtypedb_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtypedb',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='media/testtypes'),
        ),
    ]
