# Generated by Django 5.2.3 on 2025-07-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_testtypedb_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdb',
            old_name='test_belong_to',
            new_name='test_group',
        ),
    ]
