# Generated by Django 5.2.3 on 2025-07-02 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_test_belong_to_testdb_test_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTMQuestionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='DTMquestions/')),
            ],
        ),
        migrations.CreateModel(
            name='DTMSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_score', models.FloatField(default=3.1)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DTMTestDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_test_name', models.CharField(max_length=200)),
                ('test_description', models.TextField(blank=True)),
                ('XP', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DTMTestGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('subject1', models.CharField(max_length=200)),
                ('subject2', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='testdb',
            name='test_group',
        ),
        migrations.CreateModel(
            name='DTMAnswerDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answer_picture', models.ImageField(blank=True, null=True, upload_to='DTManswers/')),
                ('is_true', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DTManswers', to='api.dtmquestiondb')),
            ],
        ),
        migrations.AddField(
            model_name='dtmquestiondb',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DTMquestions', to='api.dtmsubject'),
        ),
        migrations.AddField(
            model_name='dtmsubject',
            name='dtm_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DTMsubjects', to='api.dtmtestdb'),
        ),
        migrations.AddField(
            model_name='dtmtestdb',
            name='dtm_test_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DTMtests', to='api.dtmtestgroups'),
        ),
    ]
