# Generated by Django 5.2.3 on 2025-07-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_dtmquestiondb_dtmsubject_dtmtestdb_dtmtestgroups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTestTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='media/testtypes')),
                ('link_for_test', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='TestTypeDB',
        ),
        migrations.AlterModelOptions(
            name='dtmtestdb',
            options={'verbose_name': 'Dtm Test', 'verbose_name_plural': 'Dtm Testlar'},
        ),
        migrations.AlterModelOptions(
            name='dtmtestgroups',
            options={'verbose_name': 'Dtm Test Guruhlari', 'verbose_name_plural': 'Dtm Test Guruhlari'},
        ),
        migrations.AlterModelOptions(
            name='testdb',
            options={'verbose_name': 'Xalqaro Universitet Testi', 'verbose_name_plural': 'Xalqaro Universitet Testlari'},
        ),
        migrations.AlterModelOptions(
            name='universitydb',
            options={'verbose_name': 'Xalqaro Universitet', 'verbose_name_plural': 'Xalqaro Universitetlar'},
        ),
    ]
