# Generated by Django 5.2.3 on 2025-07-03 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_testsubmission_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTMTestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('total_correct', models.IntegerField(default=0)),
                ('XP', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dtmtestdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DTM Test Submission',
                'verbose_name_plural': 'DTM Test Submissions',
            },
        ),
        migrations.CreateModel(
            name='DTMAnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct_answer', models.BooleanField(default=False)),
                ('chosen_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dtmanswerdb')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dtmquestiondb')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.dtmtestsubmission')),
            ],
        ),
    ]
