# Generated by Django 5.2.3 on 2025-07-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_dtmtestsubmission_dtmanswersubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtmtestsubmission',
            name='total_correct',
        ),
        migrations.AddField(
            model_name='dtmtestsubmission',
            name='total_score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
