# Generated by Django 5.2.3 on 2025-07-03 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_dtmtestsubmission_total_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtmanswersubmission',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_submission_answers', to='api.dtmtestsubmission'),
        ),
        migrations.AlterField(
            model_name='dtmtestsubmission',
            name='total_score',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='DTMSubjectsSubmissionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_submission_subject', to='api.dtmtestsubmission')),
            ],
        ),
    ]
