# Generated by Django 5.2.3 on 2025-07-03 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_dtmanswersubmission_submission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtmanswersubmission',
            name='submission',
        ),
        migrations.AddField(
            model_name='dtmanswersubmission',
            name='submission_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submission_answers', to='api.dtmsubjectssubmissiondb'),
            preserve_default=False,
        ),
    ]
