# Generated by Django 5.2.3 on 2025-07-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_dtmanswersubmission_submission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtmsubjectssubmissiondb',
            old_name='correct',
            new_name='total_correct_answered',
        ),
    ]
