# Generated by Django 5.2.3 on 2025-07-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_correct_dtmsubjectssubmissiondb_total_correct_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtmtestdb',
            name='time',
            field=models.PositiveIntegerField(default=0, help_text='Time in minutes'),
        ),
    ]
