# Generated by Django 5.2.3 on 2025-07-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_dtmtestdb_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtmsubjectssubmissiondb',
            name='dtm_subject_id',
            field=models.IntegerField(default=0),
        ),
    ]
