# Generated by Django 5.2.3 on 2025-07-04 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_phone_number_user_telegram_id_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_name', models.CharField(max_length=200)),
                ('tariff_price', models.FloatField(default=0)),
                ('is_free', models.BooleanField(default=True)),
                ('max_usage_of_solving_test', models.IntegerField(default=20)),
                ('max_usage_of_creating_test_by_AI', models.IntegerField(default=2)),
                ('is_accessed_teacher_panel', models.BooleanField()),
                ('duration_days', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tariff_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='active_tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tariff'),
        ),
    ]
