# Generated by Django 5.2.3 on 2025-07-08 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_tariff_user_tariff_expiry_user_active_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicQuestionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='questions/')),
            ],
        ),
        migrations.CreateModel(
            name='ClassicSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('point_for_each_question', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ClassicSubjectsSubmissionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('total_correct_answered', models.IntegerField(default=0)),
                ('subject_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClassicAnswerDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answer_picture', models.ImageField(blank=True, null=True, upload_to='answers/')),
                ('is_true', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.classicquestiondb')),
            ],
        ),
        migrations.AddField(
            model_name='classicquestiondb',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.classicsubject'),
        ),
        migrations.CreateModel(
            name='ClassicAnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct_answer', models.BooleanField(default=False)),
                ('chosen_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classicanswerdb')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classicquestiondb')),
                ('submission_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_answers', to='api.classicsubjectssubmissiondb')),
            ],
        ),
        migrations.CreateModel(
            name='ClassicTestDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('time', models.PositiveIntegerField(default=0, help_text='Time in minutes')),
                ('created_by', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classic Test',
                'verbose_name_plural': 'Classic Testlar',
            },
        ),
        migrations.AddField(
            model_name='classicsubject',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.classictestdb'),
        ),
        migrations.CreateModel(
            name='ClassicTestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.FloatField(default=0)),
                ('total_correct', models.IntegerField()),
                ('XP', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classictestdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'classic Test Submission',
                'verbose_name_plural': 'Classic Test Submissions',
            },
        ),
        migrations.AddField(
            model_name='classicsubjectssubmissiondb',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_submission_subject', to='api.classictestsubmission'),
        ),
    ]
