# Generated by Django 5.2.3 on 2025-07-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_classicquestiondb_classicsubject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classictestdb',
            name='price_for_test',
            field=models.FloatField(default=0),
        ),
    ]
