# Generated by Django 5.2.3 on 2025-07-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_classictestdb_price_for_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='classictestdb',
            name='is_olympiad_test',
            field=models.BooleanField(default=False),
        ),
    ]
