# Generated by Django 5.2.3 on 2025-07-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_classictestdb_is_olympiad_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classicanswersubmission',
            name='submission_subject',
        ),
        migrations.AlterModelOptions(
            name='classictestsubmission',
            options={'verbose_name': 'Test Submission', 'verbose_name_plural': 'Test Submissions'},
        ),
        migrations.RemoveField(
            model_name='classictestsubmission',
            name='XP',
        ),
        migrations.RemoveField(
            model_name='classictestsubmission',
            name='total_score',
        ),
        migrations.AddField(
            model_name='classicanswersubmission',
            name='submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.classictestsubmission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classictestsubmission',
            name='total_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ClassicSubjectsSubmissionDB',
        ),
    ]
