# Generated by Django 5.2.3 on 2025-07-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_classicanswersubmission_submission_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classictestsubmission',
            options={'verbose_name': 'Classic Test Submission', 'verbose_name_plural': 'Classic Test Submissions'},
        ),
        migrations.AddField(
            model_name='classictestsubmission',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
