# Generated by Django 5.2.3 on 2025-07-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_user_telegram_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telegram_username',
            new_name='telegram_name',
        ),
    ]
