# Generated by Django 5.2.3 on 2025-07-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_telegram_username_user_telegram_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='XP_earned',
            field=models.IntegerField(default=0),
        ),
    ]
