# Generated by Django 5.2.3 on 2025-07-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_user_xp_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='classictestdb',
            name='picture',
            field=models.ImageField(default=1, upload_to='classic_test_pictures'),
            preserve_default=False,
        ),
    ]
