# Generated by Django 5.2.3 on 2025-07-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_classictestdb_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classictestdb',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='classic_test_pictures'),
        ),
    ]
