# Generated by Django 5.2.3 on 2025-07-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_classictestdb_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classictestdb',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='test_pictures/'),
        ),
    ]
