# Generated by Django 5.2.3 on 2025-07-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_classictestdb_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='classictestdb',
            name='qr_code_picture',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code_classic/'),
        ),
        migrations.AddField(
            model_name='classictestdb',
            name='unique_code',
            field=models.IntegerField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
