# Generated by Django 5.2.3 on 2025-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_classictestdb_qr_code_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classictestdb',
            name='difficulty',
            field=models.CharField(default='uzbek', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classictestdb',
            name='test_language',
            field=models.CharField(default='uzbek', max_length=30),
            preserve_default=False,
        ),
    ]
