# Generated by Django 5.2.3 on 2025-07-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_classictestdb_difficulty_classictestdb_test_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classictestdb',
            name='difficulty',
            field=models.CharField(default='qiyin', max_length=20),
        ),
        migrations.AlterField(
            model_name='classictestdb',
            name='test_language',
            field=models.CharField(default='english', max_length=30),
        ),
    ]
