# Generated by Django 5.2.3 on 2025-07-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_classictestdb_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classictestdb',
            name='total_number_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
