# Generated by Django 5.2.3 on 2025-07-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_classictestdb_total_number_of_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitydb',
            old_name='university_picture',
            new_name='university_logo_picture',
        ),
        migrations.AddField(
            model_name='universitydb',
            name='contract_sum_finish',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='universitydb',
            name='contract_sum_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='universitydb',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='universitydb',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='universitydb',
            name='location',
            field=models.TextField(default='Tashkent'),
        ),
        migrations.AddField(
            model_name='universitydb',
            name='phone_number',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitydb',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='universitydb',
            name='university_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/universities'),
        ),
        migrations.AddField(
            model_name='universitydb',
            name='website_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
