# Generated by Django 5.2.3 on 2025-07-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_university_picture_universitydb_university_logo_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitydb',
            old_name='university_logo_picture',
            new_name='university_picture',
        ),
    ]
