# Generated by Django 5.2.3 on 2025-07-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_university_logo_picture_universitydb_university_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitydb',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
    ]
