# Generated by Django 5.2.3 on 2025-07-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_universitydb_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitydb',
            name='university_type',
            field=models.CharField(choices=[('xalqaro', 'Xalqaro'), ('xususiy', 'Xususiy')], default='xalqaro', max_length=7),
        ),
    ]
