# Generated by Django 5.2.3 on 2025-07-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_universitydb_university_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='facultydb',
            name='contact_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facultydb',
            name='contract_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultydb',
            name='duration',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='facultydb',
            name='schoolarship_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultydb',
            name='test_subjects',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facultydb',
            name='education_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.educationlanguage'),
        ),
    ]
