# Generated by Django 5.2.3 on 2025-07-21 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_educationlanguage_facultydb_contact_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdb',
            name='university_root',
            field=models.ForeignKey(blank=True, help_text='Choose if university is not faculty based test', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.universitydb'),
        ),
        migrations.AddField(
            model_name='universitydb',
            name='is_faculty_based',
            field=models.BooleanField(default=True),
        ),
    ]
