# Generated by Django 5.2.3 on 2025-07-21 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_testdb_university_root_universitydb_is_faculty_based'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdb',
            name='test_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.educationlanguage'),
        ),
    ]
