# Generated by Django 5.2.3 on 2025-07-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_testdb_test_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubmission',
            name='status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('best', 'Worst'), ('better', 'Better'), ('good', 'Good'), ('worst', 'Worst')], default='better', max_length=10),
        ),
    ]
