# Generated by Django 5.2.3 on 2025-07-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_testsubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubmission',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
