# Generated by Django 5.2.3 on 2025-07-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_testsubmission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classictestdb',
            name='unique_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='testsubmission',
            name='status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('best', 'Best'), ('better', 'Better'), ('good', 'Good'), ('worst', 'Worst')], default='better', max_length=10),
        ),
    ]
