# Generated by Django 5.2.3 on 2025-07-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_classictestdb_unique_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariff',
            old_name='max_usage_of_solving_test',
            new_name='max_usage_of_solving_ielts_test',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
