# Generated by Django 5.2.3 on 2025-07-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_rename_max_usage_of_solving_test_tariff_max_usage_of_solving_ielts_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='tariff_price',
            field=models.IntegerField(default=0),
        ),
    ]
