# Generated by Django 5.2.3 on 2025-08-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_dtm_subjects_dtm_test_language_question_answer_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_type',
        ),
        migrations.AddField(
            model_name='dtm_subjects',
            name='test_type',
            field=models.CharField(choices=[('main_subject', 'Main Subject'), ('mandatory_subject', 'Mandatory Subject')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
