from .international_university_testDB import *
from .international_universityDB import *
from .international_university_test_result import *
from .userDB import User
from .DTMtestDB import *
from .test_typesDB import *
from .dtm_test_result import *
from .tariffDB import *
from .ClassicTestDB import *
from .ClassticTestResultDB import *